IntermediateAssessment/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntermediateAssessment.Storage;

namespace IntermediateAssessment.Controllers
{
    /// <summary>
    /// Формирование отчетов
    /// </summary>
    public class ExercisesController : DbController
    {
        /// <summary>
        /// Дашборд заданий
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // https://docs.microsoft.com/ru-ru/dotnet/csharp/linq/perform-left-outer-joins

            // Список всех студентов
            var list = db.Students.OrderBy(x => x.FileNumber).ToList();
            DateTime now = DateTime.Now;
            // Количество доступных РК
            int count = db.Assessments.Where(x => x.StartTime < now).Count();
            int width = (int)Math.Round(Math.Sqrt(count * list.Count() + 0.51));
            var m = new Models.ExercisesMatrix();
            int nstudent = 0;
            int nassessment = 1;
            while (nstudent < list.Count())
            {
                var il = new List<Models.MatrixItem>();
                for (int i = 0; i < width; i++)
                {
                    var item = new Models.MatrixItem(list[nstudent].Exercise(nassessment));
                    il.Add(item);
                    // Следующая ячейка
                    if (++nassessment > count)
                    {
                        nassessment = 1;
                        nstudent++;
                        if (nstudent >= list.Count()) { break; }
                    }
                }
                m.Items.Add(il);
            }
            return View(m);
        }

        /// <summary>
        /// Список студентов
        /// </summary>
        /// <returns></returns>
        public ActionResult Report()
        {
            DateTime now = DateTime.Now;
            // Доступные РК
            var alist = db.Assessments
                .Where(x => x.StartTime < now)
                .OrderBy(x => x.Number).ToList();
            int count = alist.Count();

            // Список групп
            var groups = db.Students.Select(a => a.Group).Distinct()
                .Select(a => new Models.Group() { GroupName = a }).ToList();

            foreach (Models.Group group in groups)
            {
                var students = db.Students.Where(a => a.Group == group.GroupName).OrderBy(a => a.LastName).ToList();
                foreach (var student in students)
                {
                    group.Students.Add(new Models.Student(student, count));
                }
            }

            // Данные для отетча
            var report = new Models.Report(alist, groups);

            // Количество столбцов в отчете: фамилия, имя, группа, и на каждый РК
            ViewBag.ColSpan = 3 + count;

            return View(report);
        }
    }
}

IntermediateAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="padding-top:0px;">
    <div id="navigationMenu">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href=@Url.Action("Index", "Home")><img src="~/Images/csharp.png" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Рубежные контроли", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item active dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Отчеты
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Статистика", "Index", "Exercises", null, new { @class = "nav-link" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("Список", "Report", "Exercises", null, new { @class = "nav-link" })
                        </div>
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Администрирование", "Admin", "Home", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="mailto:sbannikov@croc.ru">Банников С.Н.</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>